-- Add 50+ fun facts; idempotent on fact_text. Daily picker uses day-of-year % count (see page.tsx).

insert into public.fun_facts (fact_text, category, show_date)
select v.fact, v.cat, null::date
from (values
  ('Honey never spoils — archaeologists have sampled honey thousands of years old.', 'science'),
  ('Bananas are berries, but strawberries are not — botany loves exceptions.', 'science'),
  ('Octopuses have three hearts and blue blood rich in copper.', 'science'),
  ('A day on Venus is longer than a Venus year — slow spin, fast orbit.', 'space'),
  ('Wombat droppings are cube-shaped, which helps mark territory on rocks.', 'nature'),
  ('Shouting does not speed up Wi-Fi — patience and a reboot sometimes do.', 'tech'),
  ('The Eiffel Tower grows several centimetres taller on hot summer days.', 'science'),
  ('There is enough gold in Earth''s core to coat the surface — if we could reach it.', 'science'),
  ('Your nose and ears keep changing shape slowly through life — mostly cartilage.', 'science'),
  ('Cleopatra lived closer in time to the Moon landing than to the Great Pyramid''s construction.', 'history'),
  ('Oxford University is older than the Aztec Empire.', 'history'),
  ('A group of flamingos is called a flamboyance.', 'nature'),
  ('Some snails can sleep for years when conditions are too dry.', 'nature'),
  ('The adult human body has on the order of tens of trillions of cells.', 'science'),
  ('Water expands when it freezes — ice floats so lakes freeze from the top down.', 'science'),
  ('Telugu has absorbed vocabulary from Sanskrit, Persian, Urdu, and English over centuries.', 'telugu'),
  ('The use of zero as a number was pioneered in the Indian subcontinent.', 'india'),
  ('The Taj Mahal''s white marble reflects light differently from dawn to dusk.', 'india'),
  ('Mysore sandal soap has been crafted since 1916 — a small luxury with history.', 'india'),
  ('Filter coffee and masala chai both have loyal fans — pick your morning joy.', 'food'),
  ('Sunlight takes about eight minutes to travel from the Sun to Earth.', 'space'),
  ('Jupiter''s Great Red Spot is a storm wider than our planet.', 'space'),
  ('A teaspoon of neutron-star material would weigh billions of tons on Earth.', 'space'),
  ('Fungi help trees share nutrients through networks nicknamed the wood wide web.', 'nature'),
  ('Cows can form social bonds and may get stressed when separated from friends.', 'nature'),
  ('The first computer "bug" was a real moth found in a Harvard relay in 1947.', 'tech'),
  ('QWERTY layouts were partly designed to keep early typebars from jamming.', 'tech'),
  ('A big cumulus cloud can weigh as much as a herd of elephants — yet it floats.', 'science'),
  ('Laughter can briefly lower stress hormones and lift mood.', 'wellness'),
  ('A ten-minute walk outdoors often improves focus the same day.', 'wellness'),
  ('The Mediterranean "diet" is also about long meals with people you like.', 'wellness'),
  ('Turmeric, cumin, and cardamom travelled trade routes for centuries.', 'food'),
  ('Black pepper was once so prized traders called it black gold.', 'history'),
  ('Limestone regions often hold fossils of ancient seas — stone with stories.', 'science'),
  ('Cricket''s modern rules took shape in England and spread with empire and trade.', 'cricket'),
  ('Swing bowling links seam position, polish, humidity, and physics — not luck alone.', 'cricket'),
  ('A total solar eclipse is the Moon passing in front of the Sun — use safe filters.', 'space'),
  ('Fingerprints form before birth and stay unique through life.', 'science'),
  ('Reading fiction can train empathy — you practise other points of view.', 'wellness'),
  ('"Goodbye" shortened from "God be with ye" over centuries of speech.', 'history'),
  ('Dolphins may rest one brain hemisphere at a time, one eye still watching.', 'nature'),
  ('Some jellyfish can revert to an earlier life stage under stress — a rare trick.', 'nature'),
  ('Himalayan peaks still rise slowly as tectonic plates push upward.', 'science'),
  ('The Pacific Ocean is wider than the Moon''s diameter.', 'space'),
  ('Leap years exist because Earth''s orbit takes about 365.24 days.', 'science'),
  ('Your heart beats roughly 100,000 times a day, mostly on autopilot.', 'wellness'),
  ('Tollywood (Telugu cinema) is among the world''s largest film industries by output.', 'telugu'),
  ('A genuine smile uses fewer muscles than a dramatic frown — save energy for friends.', 'wellness'),
  ('Rainbows are full circles — pilots sometimes see rings from above.', 'science'),
  ('Lightning strikes Earth roughly a hundred times per second worldwide.', 'science'),
  ('The speed of sound in air is about 343 metres per second at room temperature.', 'science'),
  ('Glass is an amorphous solid — it flows so slowly that old windows barely thicken.', 'science'),
  ('Peanuts are legumes that grow underground, not tree nuts.', 'food'),
  ('A blue whale''s heart can weigh as much as a small car.', 'nature'),
  ('The Great Wall of China is not visible to the naked eye from low Earth orbit.', 'history'),
  ('Sachin Tendulkar is the only player to score one hundred international centuries.', 'cricket'),
  ('M.S. Dhoni is known for calm finishes — "Captain Cool" is not just a nickname.', 'cricket'),
  ('Virat Kohli has set batting records across all three international formats.', 'cricket'),
  ('Anil Kumble once took all ten wickets in a Test innings — rare perfection.', 'cricket'),
  ('Sunil Gavaskar faced the fiercest West Indies pace attacks without a helmet early on.', 'cricket'),
  ('Hyderabad once had its own mint and diamond trade — pearls and gems in city lore.', 'india'),
  ('The Charminar was built in 1591 — still the heart of Old Hyderabad selfies.', 'india'),
  ('Pongal marks the harvest in Tamil Nadu; Sankranti lights skies across states.', 'india'),
  ('Telugu New Year Ugadi begins with neem and jaggery — bitter and sweet together.', 'telugu'),
  ('Rayalaseema cuisine loves spicy gunpowder chutney and sun-dried chillies.', 'food'),
  ('Kadapa district is named for a gate (Kadapa) in old fort routes.', 'india'),
  ('The Indian Space Research Organisation launched Chandrayaan and Mangalyaan missions.', 'space'),
  ('ISRO''s PSLV has launched satellites for many countries — rideshare to orbit.', 'space'),
  ('The human eye distinguishes about a million colours in good light.', 'science'),
  ('Coffee beans are seeds of a fruit often called a coffee cherry.', 'food'),
  ('Chocolate was a bitter drink in Mesoamerica before sugar met cocoa in Europe.', 'history'),
  ('The first email was sent in the 1970s — "@" chose user from machine neatly.', 'tech'),
  ('ASCII is just 128 codes — enough to bootstrap everything you see online.', 'tech'),
  ('Your gut has its own nervous system, sometimes called the second brain.', 'wellness'),
  ('Deep breaths before a message can save a friendship — pause beats regret.', 'wellness'),
  ('Meteor showers are Earth passing through comet debris — nature''s fireworks.', 'space'),
  ('Polaris will not be the north star forever — Earth''s axis slowly precesses.', 'space'),
  ('Sanskrit is a classical language with precise grammar studied for millennia.', 'india'),
  ('The decimal system spread globally from Indian mathematicians via Arab scholars.', 'history'),
  ('Chess spread from India''s chaturanga through Persia to medieval Europe.', 'history'),
  ('Monsoon rains refill India''s rivers — the whole subcontinent waits for the wind shift.', 'india'),
  ('A single cloud can hold billions of water droplets — each one tiny alone.', 'science'),
  ('Sea turtles navigate using Earth''s magnetic field across entire oceans.', 'nature'),
  ('Crows remember human faces — be kind, they might tell their friends.', 'nature'),
  ('Sloths only leave the tree about once a week — low-energy lifestyle goals.', 'nature'),
  ('The Sahara was once green — climate shifts rewrite maps over millennia.', 'history'),
  ('The Pacific Ring of Fire hosts most of the world''s active volcanoes.', 'science'),
  ('Diamond and graphite are both pure carbon — structure changes everything.', 'science'),
  ('Steel is mostly iron with a pinch of carbon — small change, huge strength.', 'science'),
  ('The first photograph took hours of exposure — sitters used neck braces.', 'history'),
  ('Velcro was inspired by burrs sticking to a dog''s fur — nature invented it first.', 'tech'),
  ('Bubble wrap was originally marketed as textured wallpaper — happy accident.', 'history'),
  ('Post-it notes came from a "failed" weak adhesive — wrong for tape, right for paper.', 'tech'),
  ('Rubber balls bounce because polymers store and release elastic energy.', 'science'),
  ('A year on Mercury is shorter than a day on Mercury — sunrises are rare.', 'space'),
  ('Saturn would float in a giant bathtub — less dense than water overall.', 'space'),
  ('Neutron stars spin hundreds of times per second — cosmic lighthouses.', 'space'),
  ('You share about 60 percent DNA with a banana — common chemistry of life.', 'science'),
  ('Koalas have fingerprints so like humans they could confuse old crime labs.', 'nature'),
  ('Axolotls can regrow limbs and parts of the heart — regeneration superstars.', 'nature'),
  ('The shortest war in history lasted about 38 to 45 minutes — Anglo-Zanzibar 1896.', 'history'),
  ('Vatican City is the world''s smallest country by area.', 'history'),
  ('Canada has more lakes than the rest of the world combined — by some counts.', 'nature'),
  ('Antarctica is the world''s largest desert by dryness, not sand.', 'science'),
  ('The human skeleton renews roughly every decade — you are never quite the same bones.', 'science'),
  ('Smell is the sense most linked to memory — one whiff can time-travel.', 'science'),
  ('Typing "thank you" in a group chat costs nothing and lifts the whole thread.', 'wellness'),
  ('Buddy groups that share one meal a month stay closer than chat-only threads.', 'wellness')
) as v(fact, cat)
where not exists (
  select 1 from public.fun_facts ff where ff.fact_text = v.fact
);
